/**************************************************************************************************
 * project
 * Description - Rkm0802 - Employee Management
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.rkm.rkm0802;

import zebra.data.ParamEntity;

public interface Rkm0802Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getInsert(ParamEntity paramEntity) throws Exception;
	public ParamEntity getUpdate(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeSave(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeDelete(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeExport(ParamEntity paramEntity) throws Exception;
}