/**************************************************************************************************
 * project
 * Description - Rkm0206 - Other Income T2
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.rkm.rkm0206;

import zebra.data.ParamEntity;

public interface Rkm0206Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getEdit(ParamEntity paramEntity) throws Exception;
	public ParamEntity calculateDataEntry(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeSave(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeComplete(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeDelete(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeExport(ParamEntity paramEntity) throws Exception;
}