<%/************************************************************************************************
* Description - Sba0202 - Organisation Management
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	SysOrg sysOrg = (SysOrg)paramEntity.getObject("sysOrg");
	String dateFormat = ConfigUtil.getProperty("format.date.java");
	String intFormat = ConfigUtil.getProperty("format.default.integer");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconHKAccount.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var orgId = "<%=sysOrg.getOrgId()%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnEdit" caption="button.com.edit" iconClass="fa-edit"/>
			<ui:button id="btnDelete" caption="button.com.delete" iconClass="fa-save"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<table class="tblDefault">
		<tr>
			<td class="tdDefault Lt" style="width:250px;height:80px;vertical-align:bottom">
				<img id="img<%=sysOrg.getOrgId()%>" src="<%=sysOrg.getLogoPath()%>" class="imgDis" title="<%=sysOrg.getLegalName()%>"/>
			</td>
		</tr>
	</table>
	<div class="verGap4"></div>
	<table class="tblEdit">
		<colgroup>
			<col width="14%"/>
			<col width="36%"/>
			<col width="14%"/>
			<col width="36%"/>
		</colgroup>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sba0202.header.orgId"/></th>
			<td class="tdEdit"><%=sysOrg.getOrgId()%></td>
			<th class="thEdit Rt"><mc:msg key="sba0202.header.abn"/></th>
			<td class="tdEdit"><%=CommonUtil.getFormatString(sysOrg.getAbn(), "?? ??? ???")%></td>
		</tr>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sba0202.header.legalName"/></th>
			<td class="tdEdit"><%=sysOrg.getLegalName()%></td>
			<th class="thEdit Rt"><mc:msg key="sba0202.header.tradingName"/></th>
			<td class="tdEdit"><%=sysOrg.getTradingName()%></td>
		</tr>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sba0202.header.registeredDate"/></th>
			<td class="tdEdit"><%=CommonUtil.toString(sysOrg.getRegisteredDate(), dateFormat)%></td>
			<th class="thEdit Rt"><mc:msg key="sba0202.header.isActive"/></th>
			<td class="tdEdit"><%=CommonCodeManager.getCodeDescription("IS_ACTIVE", sysOrg.getIsActive())%></td>
		</tr>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sba0202.header.orgCategory"/></th>
			<td class="tdEdit"><%=CommonCodeManager.getCodeDescription("ORG_CATEGORY", sysOrg.getOrgCategory())%></td>
			<th class="thEdit Rt"><mc:msg key="sba0202.header.email"/></th>
			<td class="tdEdit"><%=sysOrg.getEmail()%></td>
		</tr>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sba0202.header.entityType"/></th>
			<td class="tdEdit"><%=CommonCodeManager.getCodeDescription("ENTITY_TYPE", sysOrg.getEntityType())%></td>
			<th class="thEdit Rt"><mc:msg key="sba0202.header.businessType"/></th>
			<td class="tdEdit"><%=CommonCodeManager.getCodeDescription("BUSINESS_TYPE", sysOrg.getBusinessType())%></td>
		</tr>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sba0202.header.baseType"/></th>
			<td class="tdEdit"><%=CommonCodeManager.getCodeDescription("BASE_TYPE", sysOrg.getBaseType())%></td>
			<th class="thEdit Rt"><mc:msg key="sba0202.header.wageType"/></th>
			<td class="tdEdit"><%=CommonCodeManager.getCodeDescription("WAGE_TYPE", sysOrg.getWageType())%></td>
		</tr>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sba0202.header.rRangeFrom"/></th>
			<td class="tdEdit"><%=CommonUtil.getNumberMask(sysOrg.getRevenueRangeFrom(), intFormat)%></td>
			<th class="thEdit Rt"><mc:msg key="sba0202.header.rRangeTo"/></th>
			<td class="tdEdit"><%=CommonUtil.getNumberMask(sysOrg.getRevenueRangeTo(), intFormat)%></td>
		</tr>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sba0202.header.postalAddress"/></th>
			<td class="tdEdit" colspan="3"><%=sysOrg.getPostalAddress()%></td>
		</tr>
	</table>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>