<%/************************************************************************************************
* Description - Sba0402 - Financial Period Type
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	SysFinancialPeriod sysFinancialPeriod = (SysFinancialPeriod)paramEntity.getObject("sysFinancialPeriod");
	String dateFormat = ConfigUtil.getProperty("format.date.java");
	int currentYear = CommonUtil.toInt(CommonUtil.getSysdate("YYYY"));

	String financialYear[] = CommonUtil.split(sysFinancialPeriod.getFinancialYear(), "-");
	String yearFrom = financialYear[0];
	String yearTo = financialYear[1];
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconHKAccount.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var periodYear = "<%=requestDataSet.getValue("periodYear")%>";
var quarterCode = "<%=requestDataSet.getValue("quarterCode")%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnSave" caption="button.com.save" iconClass="fa-save"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<table class="tblEdit">
		<colgroup>
			<col width="17%"/>
			<col width="33%"/>
			<col width="17%"/>
			<col width="33%"/>
		</colgroup>
		<tr>
			<th class="thEdit Rt mandatory"><mc:msg key="sba0402.header.periodYear"/></th>
			<td class="tdEdit">
				<ui:select name="periodYear" options="mandatory">
<%
				for (int i=-5; i<6; i++) {
					String seleted = (CommonUtil.equals(CommonUtil.toString(currentYear - i), sysFinancialPeriod.getPeriodYear())) ? "selected" : "";
%>
					<option value="<%=currentYear - i%>" <%=seleted%>><%=currentYear - i%></option>
<%
				}
%>
				</ui:select>
			</td>
			<th class="thEdit Rt mandatory"><mc:msg key="sba0402.header.quarterCode"/></th>
			<td class="tdEdit"><ui:ccselect name="quarterCode" codeType="QUARTER_CODE" options="mandatory" selectedValue="<%=sysFinancialPeriod.getQuarterCode()%>"/></td>
		</tr>
		<tr>
			<th class="thEdit Rt mandatory"><mc:msg key="sba0402.header.financialYear"/></th>
			<td class="tdEdit">
				<ui:select name="financialYearFrom" options="mandatory">
<%
				for (int i=-5; i<6; i++) {
					String seleted = (CommonUtil.equals(CommonUtil.toString(currentYear - i), yearFrom)) ? "selected" : "";
%>
					<option value="<%=currentYear - i%>" <%=seleted%>><%=currentYear - i%></option>
<%
				}
%>
				</ui:select>
				-
				<ui:select name="financialYearTo" options="mandatory">
<%
				for (int i=-5; i<6; i++) {
					String seleted = (CommonUtil.equals(CommonUtil.toString(currentYear - i), yearTo)) ? "selected" : "";
%>
					<option value="<%=currentYear - i%>" <%=seleted%>><%=currentYear - i%></option>
<%
				}
%>
				</ui:select>
			</td>
			<th class="thEdit Rt mandatory"><mc:msg key="sba0402.header.quarterName"/></th>
			<td class="tdEdit"><ui:ccselect name="quarterName" codeType="QUARTER_NAME" options="mandatory" selectedValue="<%=sysFinancialPeriod.getQuarterName()%>"/></td>
		</tr>
		<tr>
			<th class="thEdit Rt mandatory"><mc:msg key="sba0402.header.dateFrom"/></th>
			<td class="tdEdit"><ui:text name="dateFrom" value="<%=CommonUtil.toString(sysFinancialPeriod.getDateFrom(), dateFormat)%>" style="width:80px" options="mandatory"/></td>
			<th class="thEdit Rt mandatory"><mc:msg key="sba0402.header.dateTo"/></th>
			<td class="tdEdit"><ui:text name="dateTo" value="<%=CommonUtil.toString(sysFinancialPeriod.getDateTo(), dateFormat)%>" style="width:80px" options="mandatory"/></td>
		</tr>
	</table>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>