/**************************************************************************************************
 * project
 * Description - Sba0410 - Repayment Type
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sba.sba0410;

import zebra.data.ParamEntity;

public interface Sba0410Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getUpdate(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeUpdate(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeSave(ParamEntity paramEntity) throws Exception;
}