/**************************************************************************************************
 * project
 * Description - Rkm0602 - Repayment
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.rkm.rkm0602;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;

import project.common.extend.BaseBiz;
import project.common.module.commoncode.CommonCodeManager;
import project.conf.resource.ormapper.dao.SysRepaymentType.SysRepaymentTypeDao;
import project.conf.resource.ormapper.dao.UsrFinance.UsrFinanceDao;
import project.conf.resource.ormapper.dto.oracle.SysRepaymentType;
import project.conf.resource.ormapper.dto.oracle.UsrFinance;
import zebra.data.DataSet;
import zebra.data.ParamEntity;
import zebra.data.QueryAdvisor;
import zebra.exception.FrameworkException;
import zebra.export.ExportHelper;
import zebra.util.CommonUtil;
import zebra.util.ConfigUtil;
import zebra.util.ExportUtil;

public class Rkm0602BizImpl extends BaseBiz implements Rkm0602Biz {
	@Autowired
	private UsrFinanceDao usrFinanceDao;
	@Autowired
	private SysRepaymentTypeDao sysRepaymentTypeDao;

	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception {
		try {
			paramEntity.setSuccess(true);
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity getList(ParamEntity paramEntity) throws Exception {
		DataSet requestDataSet = paramEntity.getRequestDataSet();
		QueryAdvisor queryAdvisor = paramEntity.getQueryAdvisor();
		HttpSession session = paramEntity.getSession();
		String orgId = CommonUtil.nvl((String)session.getAttribute("OrgIdForAdminTool"), (String)session.getAttribute("OrgId"));

		try {
			queryAdvisor.setObject("orgId", orgId);
			queryAdvisor.setObject("langCode", (String)session.getAttribute("langCode"));
			queryAdvisor.setRequestDataSet(requestDataSet);
			queryAdvisor.setPagination(true);

			paramEntity.setAjaxResponseDataSet(usrFinanceDao.getRepaymentDataSetByCriteria(queryAdvisor));
			paramEntity.setTotalResultRows(queryAdvisor.getTotalResultRows());
			paramEntity.setSuccess(true);
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity getEdit(ParamEntity paramEntity) throws Exception {
		DataSet requestDataSet = paramEntity.getRequestDataSet();
		String financeId = requestDataSet.getValue("financeId");

		try {
			paramEntity.setAjaxResponseDataSet(usrFinanceDao.getFinanceDataSetByFinanceIdForUpdate(financeId));
			paramEntity.setSuccess(true);
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity exeSave(ParamEntity paramEntity) throws Exception {
		DataSet dsReq = paramEntity.getRequestDataSet();
		HttpSession session = paramEntity.getSession();
		UsrFinance usrFinance = new UsrFinance();
		SysRepaymentType sysRepaymentType = new SysRepaymentType();
		String financeId = CommonUtil.nvl(dsReq.getValue("deFinanceId"), "-1");
		String dateFormat = ConfigUtil.getProperty("format.date.java");
		String userId = (String)session.getAttribute("UserId");
		String orgId = CommonUtil.nvl((String)session.getAttribute("OrgIdForAdminTool"), (String)session.getAttribute("OrgId"));
		String orgCategory = CommonUtil.nvl((String)session.getAttribute("OrgCategoryForAdminTool"), (String)session.getAttribute("OrgCategory"));
		String saveType = (CommonUtil.equals(financeId, "-1")) ? "I" : "U";
		int result = -1;

		try {
			if (CommonUtil.equals(saveType, "I")) {
				usrFinance.setFinanceId(CommonUtil.uid());
			} else {
				usrFinance = usrFinanceDao.getFinanceById(financeId);
			}

			usrFinance.setFinanceYear(dsReq.getValue("financialYear"));
			usrFinance.setQuarterName(dsReq.getValue("quarterName"));
			usrFinance.setOrgId(orgId);
			usrFinance.setFinanceEntryType(CommonCodeManager.getCodeByConstants("FINANCE_ENTRY_TYPE_REP"));
			sysRepaymentType = sysRepaymentTypeDao.getRepaymentTypeByOrgCategoryRepaymentType(orgCategory, dsReq.getValue("deRepaymentType"));
			usrFinance.setFinanceTypeId(sysRepaymentType.getRepaymentTypeId());
			usrFinance.setFinanceDate(CommonUtil.toDate(dsReq.getValue("deDate"), dateFormat));
			usrFinance.setRepaymentAmt(CommonUtil.toDouble(dsReq.getValue("deRepaymentAmt")));
			usrFinance.setDescription(dsReq.getValue("deRemark"));

			if (CommonUtil.equals(saveType, "I")) {
				usrFinance.setIsCompleted("N");
				usrFinance.setInsertUserId(userId);
				usrFinance.setInsertDate(CommonUtil.getSysdateAsDate());

				result = usrFinanceDao.insert(usrFinance);
			} else {
				usrFinance.setUpdateUserId(userId);
				usrFinance.setUpdateDate(CommonUtil.getSysdateAsDate());

				result = usrFinanceDao.update(financeId, usrFinance);
			}

			if (result <= 0) {
				throw new FrameworkException("E801", getMessage("E801", paramEntity));
			}

			paramEntity.setSuccess(true);
			paramEntity.setMessage("I801", getMessage("I801", paramEntity));
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity exeComplete(ParamEntity paramEntity) throws Exception {
		DataSet requestDataSet = paramEntity.getRequestDataSet();
		String chkForDel = requestDataSet.getValue("chkForDel");
		String expenseIds[] = CommonUtil.splitWithTrim(chkForDel, ConfigUtil.getProperty("delimiter.record"));
		int result = 0;

		try {
			result = usrFinanceDao.exeCompleteByFinanceIds(expenseIds);

			if (result <= 0) {
				throw new FrameworkException("E801", getMessage("E801", paramEntity));
			}

			paramEntity.setSuccess(true);
			paramEntity.setMessage("I801", getMessage("I801", paramEntity));
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity exeDelete(ParamEntity paramEntity) throws Exception {
		DataSet requestDataSet = paramEntity.getRequestDataSet();
		String chkForDel = requestDataSet.getValue("chkForDel");
		String financeIds[] = CommonUtil.splitWithTrim(chkForDel, ConfigUtil.getProperty("delimiter.record"));
		int result = 0;

		try {
			result = usrFinanceDao.deleteByFinanceIds(financeIds);

			if (result <= 0) {
				throw new FrameworkException("E801", getMessage("E801", paramEntity));
			}

			paramEntity.setSuccess(true);
			paramEntity.setMessage("I801", getMessage("I801", paramEntity));
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity exeExport(ParamEntity paramEntity) throws Exception {
		DataSet requestDataSet = paramEntity.getRequestDataSet();
		QueryAdvisor queryAdvisor = paramEntity.getQueryAdvisor();
		HttpSession session = paramEntity.getSession();
		String orgId = CommonUtil.nvl((String)session.getAttribute("OrgIdForAdminTool"), (String)session.getAttribute("OrgId"));
		ExportHelper exportHelper;
		String columnHeader[], fileHeader[];
		String pageTitle, fileName;
		String fileType = requestDataSet.getValue("fileType");
		String dataRange = requestDataSet.getValue("dataRange");

		try {
			pageTitle = "Repayment List";
			fileName = "RepaymentList";
			columnHeader = new String[] {"FINANCE_DATE", "FINANCE_TYPE_DESC", "REPAYMENT_AMT", "IS_COMPLETED", "DESCRIPTION"};
			fileHeader = new String[] {"Date", "Repayment Type", "Amount", "Is Completed", "Description"};

			exportHelper = ExportUtil.getExportHelper(fileType);
			exportHelper.setPageTitle(pageTitle);
			exportHelper.setColumnHeader(columnHeader);
			exportHelper.setFileHeader(fileHeader);
			exportHelper.setFileName(fileName);
			exportHelper.setPdfWidth(1000);

			queryAdvisor.setObject("orgId", orgId);
			queryAdvisor.setObject("langCode", (String)session.getAttribute("langCode"));
			queryAdvisor.setRequestDataSet(requestDataSet);
			if (CommonUtil.containsIgnoreCase(dataRange, "all"))
				queryAdvisor.setPagination(false);
			else {
				queryAdvisor.setPagination(true);
			}

			exportHelper.setSourceDataSet(usrFinanceDao.getRepaymentDataSetByCriteria(queryAdvisor));

			paramEntity.setSuccess(true);
			paramEntity.setFileToExport(exportHelper.createFile());
			paramEntity.setFileNameToExport(exportHelper.getFileName());
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}
}