/**************************************************************************************************
 * project
 * Description - Rkm0804 - Payment
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.rkm.rkm0804;

import zebra.data.ParamEntity;

public interface Rkm0804Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getEmployeeList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getWageList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getEdit(ParamEntity paramEntity) throws Exception;
	public ParamEntity calculateDataEntry(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeSave(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeDelete(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeExport(ParamEntity paramEntity) throws Exception;
}