/**************************************************************************************************
 * project
 * Description - Sys0810 - Repayment Type
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sys0810;

import zebra.data.ParamEntity;

public interface Sys0810Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getUpdate(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeUpdate(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeSave(ParamEntity paramEntity) throws Exception;
}