/**************************************************************************************************
 * project
 * Description - Sys0810 - Repayment Type
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sys0810;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;

import project.common.extend.BaseBiz;
import project.common.module.commoncode.CommonCodeManager;
import project.conf.resource.ormapper.dao.SysRepaymentType.SysRepaymentTypeDao;
import project.conf.resource.ormapper.dto.oracle.SysRepaymentType;
import zebra.data.DataSet;
import zebra.data.ParamEntity;
import zebra.data.QueryAdvisor;
import zebra.exception.FrameworkException;
import zebra.util.CommonUtil;
import zebra.util.ConfigUtil;

public class Sys0810BizImpl extends BaseBiz implements Sys0810Biz {
	@Autowired
	private SysRepaymentTypeDao sysRepaymentTypeDao;

	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception {
		try {
			paramEntity.setSuccess(true);
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity getList(ParamEntity paramEntity) throws Exception {
		DataSet requestDataSet = paramEntity.getRequestDataSet();
		QueryAdvisor queryAdvisor = paramEntity.getQueryAdvisor();
		HttpSession session = paramEntity.getSession();

		try {
			queryAdvisor.setObject("langCode", (String)session.getAttribute("langCode"));
			queryAdvisor.setRequestDataSet(requestDataSet);

			paramEntity.setAjaxResponseDataSet(sysRepaymentTypeDao.getRepaymentTypeDataSetByCriteria(queryAdvisor));
			paramEntity.setTotalResultRows(queryAdvisor.getTotalResultRows());
			paramEntity.setSuccess(true);
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity getUpdate(ParamEntity paramEntity) throws Exception {
		DataSet requestDataSet = paramEntity.getRequestDataSet();
		String repaymentTypeId = requestDataSet.getValue("repaymentTypeId");
		String repaymentTypeCode = requestDataSet.getValue("repaymentTypeCode");

		try {
			paramEntity.setObject("sysRepaymentType", sysRepaymentTypeDao.getRepaymentTypeByKeys(repaymentTypeId, repaymentTypeCode));
			paramEntity.setSuccess(true);
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity exeUpdate(ParamEntity paramEntity) throws Exception {
		DataSet requestDataSet = paramEntity.getRequestDataSet();
		HttpSession session = paramEntity.getSession();
		String repaymentTypeId = requestDataSet.getValue("repaymentTypeId");
		String repaymentTypeCode = requestDataSet.getValue("repaymentType");
		String loggedInUserId = (String)session.getAttribute("UserId");
		SysRepaymentType sysRepaymentType;
		int result = 0;

		try {
			sysRepaymentType = sysRepaymentTypeDao.getRepaymentTypeByKeys(repaymentTypeId, repaymentTypeCode);

			sysRepaymentType.setDescription(requestDataSet.getValue("description"));
			sysRepaymentType.setIsApplyGst(requestDataSet.getValue("isApplyGst"));
			sysRepaymentType.setGstPercentage(CommonUtil.toDouble(requestDataSet.getValue("gstPercentage")));
			sysRepaymentType.setAccountCode(requestDataSet.getValue("accountCode"));
			sysRepaymentType.setUpdateUserId(loggedInUserId);
			sysRepaymentType.setUpdateDate(CommonUtil.toDate(CommonUtil.getSysdate()));

			result = sysRepaymentTypeDao.updateWithKey(sysRepaymentType, repaymentTypeId, repaymentTypeCode);
			if (result <= 0) {
				throw new FrameworkException("E801", getMessage("E801", paramEntity));
			}

			paramEntity.setSuccess(true);
			paramEntity.setMessage("I801", getMessage("I801", paramEntity));
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	public ParamEntity exeSave(ParamEntity paramEntity) throws Exception {
		DataSet requestDataSet = paramEntity.getRequestDataSet();
		HttpSession session = paramEntity.getSession();
		String orgCategory = requestDataSet.getValue("orgCategory");
		String chkToSave = requestDataSet.getValue("chkToSave");
		String keyIds[] = CommonUtil.splitWithTrim(chkToSave, ConfigUtil.getProperty("delimiter.record"));
		String loggedInUserId = (String)session.getAttribute("UserId");
		DataSet existingData;
		SysRepaymentType sysRepaymentType;
		int resultInsert = 0;

		try {
			existingData = sysRepaymentTypeDao.getRepaymentTypeDataSetByOrgCategory(orgCategory);
			sysRepaymentTypeDao.deleteByOrgCategory(orgCategory);

			if (keyIds != null) {
				for (int i=0; i<keyIds.length; i++) {
					String repaymentTypeId = "", repaymentTypeCode = "";

					if (CommonUtil.startsWith(keyIds[i], "_")) {
						repaymentTypeId = "";
						repaymentTypeCode = CommonUtil.remove(keyIds[i], "_");
					} else {
						repaymentTypeId = CommonUtil.split(keyIds[i], "_")[0];
						repaymentTypeCode = CommonUtil.split(keyIds[i], "_")[1];
					}

					if (CommonUtil.isNotBlank(repaymentTypeId)) {
						int existingIndex = existingData.getRowIndex("REPAYMENT_TYPE_ID", repaymentTypeId);
						SysRepaymentType existObj = (SysRepaymentType)existingData.getRowAsDto(existingIndex, new SysRepaymentType());

						existObj.setUpdateDate(CommonUtil.toDate(CommonUtil.getSysdate()));
						existObj.setUpdateUserId(loggedInUserId);
						existObj.setSortOrder(getSortOrder(orgCategory));

						resultInsert += sysRepaymentTypeDao.insert(existObj);
					} else {
						String uid = CommonUtil.uid();

						sysRepaymentType = new SysRepaymentType();
						sysRepaymentType.setRepaymentTypeId(uid);
						sysRepaymentType.setOrgCategory(orgCategory);
						sysRepaymentType.setRepaymentType(repaymentTypeCode);
						sysRepaymentType.setDescription(CommonCodeManager.getCodeDescription("REPAYMENT_TYPE", repaymentTypeCode));
						sysRepaymentType.setIsApplyGst("Y");
						sysRepaymentType.setGstPercentage(10);
						sysRepaymentType.setSortOrder(getSortOrder(orgCategory));
						sysRepaymentType.setInsertUserId(loggedInUserId);
						sysRepaymentType.setInsertDate(CommonUtil.toDate(CommonUtil.getSysdate()));

						resultInsert += sysRepaymentTypeDao.insert(sysRepaymentType);
					}
				}

				if (resultInsert <= 0) {
					throw new FrameworkException("E801", getMessage("E801", paramEntity));
				}
			}

			paramEntity.setSuccess(true);
			paramEntity.setMessage("I801", getMessage("I801", paramEntity));
		} catch (Exception ex) {
			throw new FrameworkException(paramEntity, ex);
		}
		return paramEntity;
	}

	private String getSortOrder(String orgCategory) throws Exception {
		String ord1 = "", ord2 = "";
		DataSet ds;

		if (CommonUtil.equals(orgCategory, "A")) {
			ord1 = "01";
		} else if (CommonUtil.equals(orgCategory, "B")) {
			ord1 = "02";
		} else if (CommonUtil.equals(orgCategory, "C")) {
			ord1 = "03";
		} else if (CommonUtil.equals(orgCategory, "D")) {
			ord1 = "04";
		}

		ds = sysRepaymentTypeDao.getMaxSortOrderDataSetByOrgCategory(orgCategory);
		ord2 = CommonUtil.toString(CommonUtil.toInt(CommonUtil.substring(ds.getValue(0, 0), 2, 4))+1);
		ord2 = CommonUtil.leftPad(ord2, 2, "0");

		return ord1+ord2+"00";
	}
}