<%/************************************************************************************************
* Description - Rkm0402 - General Expense
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	String orgCategory = CommonUtil.nvl((String)session.getAttribute("OrgCategoryForAdminTool"), (String)session.getAttribute("OrgCategory"));
	String defaultPeriodYear = (String)session.getAttribute("DefaultPeriodYear");
	String defaultQuarterName = (String)session.getAttribute("DefaultQuarterName");
	String paramFinancialYear = requestDataSet.getValue("financialYear");
	String paramQuarterName = requestDataSet.getValue("quarterName");
	String paramExpenseMainType = requestDataSet.getValue("expenseMainType");
	String paramExpenseSubType = requestDataSet.getValue("expenseSubType");
	String selectedFinancialYear = CommonUtil.nvl(paramFinancialYear, defaultPeriodYear);
	String selectedQuarterName = CommonUtil.nvl(paramQuarterName, defaultQuarterName);
	String selectedExpenseMainType = CommonUtil.nvl(paramExpenseMainType);
	String selectedExpenseSubType = CommonUtil.nvl(paramExpenseSubType);
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconHKAccount.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divHeaderHolder" class="ui-layout-north"><%@ include file="/project/common/include/header.jsp"%></div>
<div id="divBodyHolder" class="ui-layout-center">
<div id="divBodyLeft" class="ui-layout-west"><%@ include file="/project/common/include/bodyLeft.jsp"%></div>
<div id="divBodyCenter" class="ui-layout-center">
<div id="divFixedPanel">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainer">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnComplete" caption="button.com.complete" iconClass="fa-check-square"/>
			<ui:button id="btnDelete" caption="button.com.delete" iconClass="fa-trash"/>
			<ui:button id="btnSearch" caption="button.com.search" iconClass="fa-search"/>
			<ui:button id="btnClear" caption="button.com.clear" iconClass="fa-refresh"/>
			<ui:button id="btnExport" caption="button.com.export" iconClass="fa-download"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divAdminToolArea"><%@ include file="/project/common/include/bodyAdminToolArea.jsp"%></div>
<div id="divSearchCriteriaArea" class="areaContainer">
	<table class="tblSearch">
		<caption><mc:msg key="page.com.searchCriteria"/></caption>
		<colgroup>
			<col width="20%"/>
			<col width="20%"/>
			<col width="30%"/>
			<col width="*"/>
		</colgroup>
		<tr>
			<td class="tdSearch">
				<label for="financialYear" class="lblEn hor mandatory"><mc:msg key="rkm0206.search.financialYear"/></label>
				<div style="float:left;padding-right:4px;">
					<ui:deSelect name="financialYear" codeType="FinancialYear" selectedValue="<%=selectedFinancialYear%>"/>
				</div>
			</td>
			<td class="tdSearch">
				<label for="quarterName" class="lblEn hor mandatory"><mc:msg key="rkm0206.search.quarter"/></label>
				<div style="float:left;padding-right:4px;">
					<ui:ccselect name="quarterName" codeType="QUARTER_NAME" selectedValue="<%=selectedQuarterName%>"/>
				</div>
			</td>
			<td class="tdSearch">
				<label for="expenseMainType" class="lblEn hor"><mc:msg key="rkm0402.search.mainType"/></label>
				<div style="float:left;padding-right:4px;">
					<ui:deSelect name="expenseMainType" codeType="ExpenseMainType" caption="==Select==" orgCategory="<%=orgCategory%>" selectedValue="<%=selectedExpenseMainType%>"/>
				</div>
			</td>
			<td class="tdSearch">
				<label for="expenseSubType" class="lblEn hor"><mc:msg key="rkm0402.search.subType"/></label>
				<div style="float:left;padding-right:4px;">
					<ui:deSelect name="expenseSubType" codeType="ExpenseSubType" caption="==Select==" orgCategory="<%=orgCategory%>" parentCode="<%=selectedExpenseMainType%>" selectedValue="<%=selectedExpenseSubType%>"/>
				</div>
			</td>
		</tr>
	</table>
</div>
<div id="divInformArea" class="areaContainer">
	<table class="tblDataEntry">
		<caption><mc:msg key="page.com.dataEntry"/></caption>
		<colgroup>
			<col width="9%"/>
			<col width="8%"/>
			<col width="13%"/>
			<col width="14%"/>
			<col width="9%"/>
			<col width="8%"/>
			<col width="8%"/>
			<col width="*"/>
			<col width="4%"/>
		</colgroup>
		<tr>
			<th class="thDataEntry mandatory"><mc:msg key="rkm0402.de.date"/></th>
			<th class="thDataEntry mandatory"><mc:msg key="rkm0402.de.types"/></th>
			<th class="thDataEntry"><mc:msg key="rkm0402.de.mainType"/></th>
			<th class="thDataEntry"><mc:msg key="rkm0402.de.subType"/></th>
			<th class="thDataEntry mandatory"><mc:msg key="rkm0402.de.grossExpense"/></th>
			<th class="thDataEntry mandatory"><mc:msg key="rkm0402.de.gst"/></th>
			<th class="thDataEntry"><mc:msg key="rkm0402.de.netExpense"/></th>
			<th class="thDataEntry mandatory"><mc:msg key="rkm0402.de.remark"/></th>
			<th class="thDataEntry"><mc:msg key="rkm0402.de.action"/></th>
		</tr>
		<tr>
			<td class="tdDataEntry Ct">
				<div style="display:inline-block;">
					<ui:hidden name="deExpenseId"/>
					<ui:hidden name="deExpenseTypeId"/>
					<ui:text name="deDate" className="ct hor" style="width:100px" checkName="rkm0206.de.date" options="mandatory" option="date"/>
					<ui:icon id="icnDataEntryDate" className="fa-calendar hor"/>
				</div>
			</td>
			<td class="tdDataEntry Ct"><ui:button id="btnDeTypes" caption="rkm0402.de.expenseTypes" iconClass="fa-caret-down"/></td>
			<td class="tdDataEntry Ct"><ui:deSelect name="deExpenseMainType" codeType="ExpenseMainType" caption="==Select==" checkName="rkm0402.de.mainType" orgCategory="<%=orgCategory%>" options="mandatory"/></td>
			<td class="tdDataEntry Ct"><ui:deSelect name="deExpenseSubType" codeType="ExpenseSubType" caption="==Select==" checkName="rkm0402.de.subType" orgCategory="<%=orgCategory%>" parentCode="<%=selectedExpenseMainType%>" options="mandatory"/></td>
			<td class="tdDataEntry Ct"><ui:text name="deGrossExpense" className="rt numeric" checkName="rkm0402.de.grossExpense" options="mandatory" option="numeric"/></td>
			<td class="tdDataEntry Ct"><ui:text name="deGst" className="rt numeric" checkName="rkm0402.de.gst" options="mandatory" option="numeric"/></td>
			<td class="tdDataEntry Ct"><ui:text name="deNetExpense" className="rt numeric" status="display"/></td>
			<td class="tdDataEntry Ct"><ui:text name="deRemark"/></td>
			<td class="tdDataEntry Ct"><ui:icon id="icnDataEntryAction" className="fa-tasks fa-lg" script="doDataEntryAction(this)"/></td>
		</tr>
	</table>
</div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanel">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainer">
	<table id="tblGrid" class="tblGrid sort autosort">
		<colgroup>
			<col width="2%"/>
			<col width="6%"/>
			<col width="15%"/>
			<col width="15%"/>
			<col width="5%"/>
			<col width="7%"/>
			<col width="7%"/>
			<col width="7%"/>
			<col width="*"/>
			<col width="6%"/>
			<col width="6%"/>
			<col width="3%"/>
		</colgroup>
		<thead>
			<tr>
				<th class="thGrid"><ui:icon id="icnCheck" className="fa-check-square-o fa-lg"/></th>
				<th class="thGrid"><mc:msg key="rkm0402.grid.date"/></th>
				<th class="thGrid"><mc:msg key="rkm0402.grid.mainType"/></th>
				<th class="thGrid"><mc:msg key="rkm0402.grid.subType"/></th>
				<th class="thGrid"><mc:msg key="rkm0402.grid.accountCode"/></th>
				<th class="thGrid"><mc:msg key="rkm0402.grid.grossExpense"/></th>
				<th class="thGrid"><mc:msg key="rkm0402.grid.gst"/></th>
				<th class="thGrid"><mc:msg key="rkm0402.grid.netExpense"/></th>
				<th class="thGrid"><mc:msg key="rkm0402.grid.remark"/></th>
				<th class="thGrid"><mc:msg key="rkm0402.grid.isCompleted"/></th>
				<th class="thGrid"><mc:msg key="page.com.updateDate"/></th>
				<th class="thGrid"><mc:msg key="page.com.action"/></th>
			</tr>
		</thead>
		<tbody id="tblGridBody">
			<tr>
				<td class="tdGridCt" colspan="12"><mc:msg key="I002"/></td>
			</tr>
		</tbody>
		<tfoot id="tblGridFoot" style="font-weight:bold;">
		</tfoot>
	</table>
</div>
<div id="divPagingArea" class="areaContainer"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<div id="divBodyRight" class="ui-layout-east"><%@ include file="/project/common/include/bodyRight.jsp"%></div>
</div>
<div id="divFooterHolder" class="ui-layout-south"><%@ include file="/project/common/include/footer.jsp"%></div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>