<%/************************************************************************************************
* Description - Rkm0402 - General Expense
*   - Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/webapp/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	String orgCategory = CommonUtil.nvl((String)session.getAttribute("OrgCategoryForAdminTool"), (String)session.getAttribute("OrgCategory"));
	String defaultPeriodYear = (String)session.getAttribute("DefaultPeriodYear");
	String defaultQuarterName = (String)session.getAttribute("DefaultQuarterName");
	String paramFinancialYear = requestDataSet.getValue("financialYear");
	String paramQuarterName = requestDataSet.getValue("quarterName");
	String paramExpenseMainType = requestDataSet.getValue("expenseMainType");
	String paramExpenseSubType = requestDataSet.getValue("expenseSubType");
	String selectedFinancialYear = CommonUtil.nvl(paramFinancialYear, defaultPeriodYear);
	String selectedQuarterName = CommonUtil.nvl(paramQuarterName, defaultQuarterName);
	String selectedExpenseMainType = CommonUtil.nvl(paramExpenseMainType);
	String selectedExpenseSubType = CommonUtil.nvl(paramExpenseSubType);
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<tag:cp key="imgIcon"/>/favicon.png">
<title><tag:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/webapp/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript">
var popup = null;
var searchResultDataCount = 0;
var expenseTypeMenu = [];

$(function() {
	/*!
	 * event
	 */
	$("#btnNew").click(function(event) {
		openPopup({mode:"New"});
	});

	$("#btnDelete").click(function(event) {
		doDelete();
	});

	$("#btnSearch").click(function(event) {
		doSearch();
	});

	$("#btnClear").click(function(event) {
		commonJs.clearSearchCriteria();
	});

	$("#icnCheck").click(function(event) {
		commonJs.toggleCheckboxes("chkForDel");
	});

	$("#icnDataEntryDate").click(function(event) {
		commonJs.openCalendar(event, "deDate");
	});

	$("#financialYear").change(function() {
		doSearch();
	});

	$("#quarterName").change(function() {
		doSearch();
	});

	$("#expenseMainType").change(function() {
		setExpenseSubType();
	});

	$("#expenseSubType").change(function() {
		doSearch();
	});

	$("#deExpenseMainType").change(function() {
		setDeExpenseSubType();
	});

	$(document).keypress(function(event) {
		if (event.which == 13) {
			var element = event.target;
		}
	});

	/*!
	 * context menus
	 */
	setExportButtonContextMenu = function() {
		ctxMenu.commonExport[0].fun = function() {exeExport(ctxMenu.commonExport[0]);};
		ctxMenu.commonExport[1].fun = function() {exeExport(ctxMenu.commonExport[1]);};
		ctxMenu.commonExport[2].fun = function() {exeExport(ctxMenu.commonExport[2]);};
		ctxMenu.commonExport[3].fun = function() {exeExport(ctxMenu.commonExport[3]);};
		ctxMenu.commonExport[4].fun = function() {exeExport(ctxMenu.commonExport[4]);};
		ctxMenu.commonExport[5].fun = function() {exeExport(ctxMenu.commonExport[5]);};

		$("#btnExport").contextMenu(ctxMenu.commonExport, {
			classPrefix:"actionButton",
			effectDuration:300,
			effect:"slide",
			borderRadius:"bottom 4px",
			displayAround:"trigger",
			position:"bottom",
			horAdjust:0
		});
	};

	setDeTypesContextMenu = function() {
		var mainMenu = {}, subMenu = [];

		commonJs.ajaxSubmit({
			url:"/common/entryTypeSupporter/getExpenseTypesForContextMenu.do",
			dataType:"json",
			data:{},
			success:function(data, textStatus) {
				var result = commonJs.parseAjaxResult(data, textStatus, "json");
				if (result.isSuccess == true || result.isSuccess == "true") {
					var ds = result.dataSet;

					if (ds.getRowCnt() > 0) {
						for (var i=0; i<ds.getRowCnt(); i++) {
							var expenseType = ds.getValue(i, "EXPENSE_TYPE");
							var parentExpenseType = ds.getValue(i, "PARENT_EXPENSE_TYPE");
							var iLevel = parseInt(ds.getValue(i, "LEVEL"));
							var isLeaf = parseInt(ds.getValue(i, "IS_LEAF"));

							if (iLevel == 1) {
								if (subMenu.length != 0) {
									expenseTypeMenu[expenseTypeMenu.length - 1].subMenu = subMenu;
									subMenu = [];
								}

								expenseTypeMenu.push({
									name:ds.getValue(i, "DESCRIPTION"),
									userData:expenseType,
									fun:function() {
									}
								});
							} else {
								subMenu.push({
									name:ds.getValue(i, "DESCRIPTION"),
									userData:parentExpenseType+"_"+expenseType,
									fun:function() {
										setDeTypeSelectboxes($(this).attr("userData"));
									}
								});
							}

							if (i == ds.getRowCnt()-1) {
								expenseTypeMenu[expenseTypeMenu.length - 1].subMenu = subMenu;
								subMenu = [];
							}
						}
					}
				} else {
					commonJs.error(result.message);
				}
			}
		});

		$("#btnDeTypes").contextMenu(expenseTypeMenu, {
			borderRadius : "4px",
			displayAround : "trigger",
			position : "bottom",
			horAdjust : 0,
			verAdjust : 0
		});
	};

	setDataEntryActionButtonContextMenu = function() {
		ctxMenu.dataEntryAction[0].fun = function() {};
		ctxMenu.dataEntryAction[1].fun = function() {};
		ctxMenu.dataEntryAction[2].fun = function() {};

		$("#icnDataEntryAction").contextMenu(ctxMenu.dataEntryAction, {
			classPrefix:"actionInGrid",
			effectDuration:300,
			borderRadius:"bottom 4px",
			displayAround:"trigger",
			position:"bottom",
			horAdjust:0
		});
	};

	/*!
	 * process
	 */
	doSearch = function() {
		commonJs.showProcMessageOnElement("tblGrid");

		setTimeout(function() {
			commonJs.ajaxSubmit({
				url:"/rkm/0402/getList.do",
				dataType:"json",
				formId:"fmDefault",
				success:function(data, textStatus) {
					var result = commonJs.parseAjaxResult(data, textStatus, "json");

					if (result.isSuccess == true || result.isSuccess == "true") {
						renderDataGridTable(result);
					}
				}
			});
		}, 100);

		setSummaryDataForAdminTool();
	};

	renderDataGridTable = function(result) {
		var ds = result.dataSet;
		var html = "", totHtml = "";
		var totGross = 0, totGst = 0, totNet = 0;

		searchResultDataCount = ds.getRowCnt();
		$("#tblGridBody").html("");
		$("#tblGridFoot").html("");

		if (ds.getRowCnt() > 0) {
			for (var i=0; i<ds.getRowCnt(); i++) {
				totGross += parseFloat(ds.getValue(i, "GROSS_AMT"));
				totGst += parseFloat(ds.getValue(i, "GST_AMT"));
				totNet += parseFloat(ds.getValue(i, "NET_AMT"));

				html += "<tr>";
				html += "<td class=\"tdGridCt\"><input type=\"checkbox\" id=\"chkForDel\" name=\"chkForDel\" class=\"chkEn inTblGrid\" value=\""+ds.getValue(i, "EXPENSE_ID")+"\"/></td>";
				html += "<td class=\"tdGridCt\"><a onclick=\"getDetail('"+ds.getValue(i, "EXPENSE_ID")+"')\" class=\"aEn\">"+ds.getValue(i, "EXPENSE_DATE")+"</a></td>";
				html += "<td class=\"tdGridLt\">"+commonJs.abbreviate(ds.getValue(i, "PARENT_EXPENSE_TYPE_DESC"), 60)+"</td>";
				html += "<td class=\"tdGridLt\">"+commonJs.abbreviate(ds.getValue(i, "EXPENSE_TYPE_DESC"), 60)+"</td>";
				html += "<td class=\"tdGridCt\">"+ds.getValue(i, "ACCOUNT_CODE")+"</td>";
				html += "<td class=\"tdGridRt\">"+commonJs.getNumberMask(ds.getValue(i, "GROSS_AMT"), "#,###.##")+"</td>";
				html += "<td class=\"tdGridRt\">"+commonJs.getNumberMask(ds.getValue(i, "GST_AMT"), "#,###.##")+"</td>";
				html += "<td class=\"tdGridRt\">"+commonJs.getNumberMask(ds.getValue(i, "NET_AMT"), "#,###.##")+"</td>";
				html += "<td class=\"tdGridLt\">"+commonJs.abbreviate(ds.getValue(i, "DESCRIPTION"), 60)+"</td>";
				html += "<td class=\"tdGridCt\">"+ds.getValue(i, "IS_COMPLETED")+"</td>";
				html += "<td class=\"tdGridCt\">"+ds.getValue(i, "ENTRY_DATE")+"</td>";
				html += "<td class=\"tdGridCt\"><i id=\"icnAction\" name=\"icnAction\" class=\"fa fa-tasks fa-lg icnEn\" incomeId=\""+ds.getValue(i, "EXPENSE_ID")+"\" onclick=\"doAction(this)\"></i></td>";
				html += "</tr>";
			}
		} else {
			html += "<tr>";
			html += "<td class=\"tdGridCt\" colspan=\"12\"><tag:msg key="I001"/></td>";
			html += "</tr>";
		}

		totHtml += "<tr>";
		totHtml += "<td class=\"tdGridCt\"></td>";
		totHtml += "<td class=\"tdGridCt\"></td>";
		totHtml += "<td class=\"tdGridCt\"><tag:msg key="rkm0402.grid.expenseTotal"/></td>";
		totHtml += "<td class=\"tdGridCt\"></td>";
		totHtml += "<td class=\"tdGridCt\"></td>";
		totHtml += "<td class=\"tdGridRt\">"+commonJs.getNumberMask(totGross, "#,###.##")+"</td>";
		totHtml += "<td class=\"tdGridRt\">"+commonJs.getNumberMask(totGst, "#,###.##")+"</td>";
		totHtml += "<td class=\"tdGridRt\">"+commonJs.getNumberMask(totNet, "#,###.##")+"</td>";
		totHtml += "<td class=\"tdGridCt\"></td>";
		totHtml += "<td class=\"tdGridCt\"></td>";
		totHtml += "<td class=\"tdGridCt\"></td>";
		totHtml += "<td class=\"tdGridCt\"></td>";
		totHtml += "</tr>";

		$("#tblGridBody").append($(html));
		$("#tblGridFoot").append($(totHtml));
		if (commonJs.browser.FireFox) {
			gridWidthAdjust = 67;
			baseHeight = $("#divScrollablePanel").height() - 1;
		} else {
			gridWidthAdjust = 72;
			baseHeight = $("#divScrollablePanel").height() - 1;
		}

		$("#tblGrid").fixedHeaderTable({
			baseDivElement:"divScrollablePanel",
			attachedPagingArea:true,
			blockElementId:"tblGrid",
			pagingAreaId:"divPagingArea",
			totalResultRows:result.totalResultRows,
			script:"doSearch",
			baseHeight:baseHeight,
			widthAdjust:gridWidthAdjust
		});

		$("[name=icnAction]").each(function(index) {
			$(this).contextMenu(ctxMenu.dataEntrySalesAction);
		});

		commonJs.hideProcMessageOnElement("tblGrid");
	};

	getDetail = function(articleId) {
		openPopup({mode:"Detail", articleId:articleId});
	};

	openPopup = function(param) {
		var url = "", header = "";
		var height = 510;

		if (param.mode == "Detail") {
			url = "/rkm/0402/getDetail.do";
			header = "<tag:msg key="rkm0402.header.popupHeaderDetail"/>";
		} else if (param.mode == "New" || param.mode == "Reply") {
			url = "/rkm/0402/getInsert.do";
			header = "<tag:msg key="rkm0402.header.popupHeaderEdit"/>";
		} else if (param.mode == "Edit") {
			url = "/rkm/0402/getUpdate.do";
			header = "<tag:msg key="rkm0402.header.popupHeaderEdit"/>";
			height = 634;
		}

		var popParam = {
			popupId:"notice"+param.mode,
			url:url,
			paramData:{
				mode:param.mode,
				articleId:commonJs.nvl(param.articleId, "")
			},
			header:header,
			blind:true,
			width:800,
			height:height
		};

		popup = commonJs.openPopup(popParam);
	};

	doDelete = function() {
		if (commonJs.getCountChecked("chkForDel") == 0) {
			commonJs.warn("<tag:msg key="I902"/>");
			return;
		}

		commonJs.confirm({
			contents:"<tag:msg key="Q002"/>",
			buttons:[{
				caption:"Yes",
				callback:function() {
					commonJs.ajaxSubmit({
						url:"/rkm/0402/exeDelete.do",
						dataType:"json",
						formId:"fmDefault",
						success:function(data, textStatus) {
							var result = commonJs.parseAjaxResult(data, textStatus, "json");

							if (result.isSuccess == true || result.isSuccess == "true") {
								commonJs.openDialog({
									type:"information",
									contents:result.message,
									blind:true,
									buttons:[{
										caption:"Ok",
										callback:function() {
											doSearch();
										}
									}]
								});
							} else {
								commonJs.error(result.message);
							}
						}
					});
				}
			}, {
				caption:"No",
				callback:function() {
				}
			}],
			blind:true
		});
	};

	doAction = function(img) {
		var articleId = $(img).attr("articleId");

		$("input:checkbox[name=chkForDel]").each(function(index) {
			if (!$(this).is(":disabled") && $(this).val() == articleId) {
				$(this).prop("checked", true);
			} else {
				$(this).prop("checked", false);
			}
		});

		ctxMenu.dataEntrySalesAction[0].fun = function() {openPopup({mode:"Edit", articleId:articleId});};
		ctxMenu.dataEntrySalesAction[1].fun = function() {doDelete();};

		$(img).contextMenu(ctxMenu.dataEntrySalesAction, {
			classPrefix:"actionInGrid",
			displayAround:"trigger",
			position:"bottom",
			horAdjust:0,
			verAdjust:2
		});
	};

	exeExport = function(menuObject) {
		$("[name=fileType]").remove();
		$("[name=dataRange]").remove();

		if (searchResultDataCount <= 0) {
			commonJs.warn("<tag:msg key="I001"/>");
			return;
		}

		commonJs.confirm({
			contents:"<tag:msg key="Q003"/>",
			buttons:[{
				caption:"Yes",
				callback:function() {
					popup = commonJs.openPopup({
						popupId:"exportFile",
						url:"/rkm/0402/exeExport.do",
						paramData:{
							fileType:menuObject.fileType,
							dataRange:menuObject.dataRange
						},
						header:"exportFile",
						blind:false,
						width:200,
						height:100
					});
					setTimeout(function() {popup.close();}, 3000);
				}
			}, {
				caption:"No",
				callback:function() {
				}
			}],
			blind:true
		});
	};

	setExpenseSubType = function() {
		drawExpenseSubTypeSelectbox();
		$("#expenseSubType").selectpicker("refresh");
	};

	drawExpenseSubTypeSelectbox = function() {
		$("#expenseSubType option").each(function(index) {
			$(this).remove();
		});

		commonJs.ajaxSubmit({
			url:"/common/entryTypeSupporter/getExpenseSubTypeForSelectbox.do",
			dataType:"json",
			data:{expenseMainType:$("#expenseMainType").val()},
			success:function(data, textStatus) {
				var result = commonJs.parseAjaxResult(data, textStatus, "json");
				if (result.isSuccess == true || result.isSuccess == "true") {
					var ds = result.dataSet;

					$("#expenseSubType").append("<option value=\"\">==Select==</option>");
					if (ds.getRowCnt() > 0) {
						for (var i=0; i<ds.getRowCnt(); i++) {
							$("#expenseSubType").append("<option value=\""+ds.getValue(i, "EXPENSE_TYPE")+"\">"+ds.getValue(i, "DESCRIPTION")+"</option>");
						}
					}
				} else {
					commonJs.error(result.message);
				}
			}
		});
	};

	setDeExpenseSubType = function() {
		drawDeExpenseSubTypeSelectbox();
		$("#deExpenseSubType").selectpicker("refresh");
	};

	drawDeExpenseSubTypeSelectbox = function() {
		$("#deExpenseSubType option").each(function(index) {
			$(this).remove();
		});

		commonJs.ajaxSubmit({
			url:"/common/entryTypeSupporter/getExpenseSubTypeForSelectbox.do",
			dataType:"json",
			data:{expenseMainType:$("#deExpenseMainType").val()},
			success:function(data, textStatus) {
				var result = commonJs.parseAjaxResult(data, textStatus, "json");
				if (result.isSuccess == true || result.isSuccess == "true") {
					var ds = result.dataSet;

					$("#deExpenseSubType").append("<option value=\"\">==Select==</option>");
					if (ds.getRowCnt() > 0) {
						for (var i=0; i<ds.getRowCnt(); i++) {
							$("#deExpenseSubType").append("<option value=\""+ds.getValue(i, "EXPENSE_TYPE")+"\">"+ds.getValue(i, "DESCRIPTION")+"</option>");
						}
					}
				} else {
					commonJs.error(result.message);
				}
			}
		});
	};

	setDeTypeSelectboxes = function(types) {
		var mainType = types.split("_")[0];
		var subType = types.split("_")[1];

		$("#deExpenseMainType").val(mainType);
		$("#deExpenseMainType").selectpicker("val", mainType);
		setTimeout(function() {
			setDeExpenseSubType();

			$("#deExpenseSubType").val(subType);
			$("#deExpenseSubType").selectpicker("val", subType);
		}, 10);
	};

	/*!
	 * load event (document / window)
	 */
	$(window).load(function() {
		setExportButtonContextMenu();
		setDeTypesContextMenu();
		setDataEntryActionButtonContextMenu();
		setExpenseSubType();
		setDeExpenseSubType();

		commonJs.setFieldDateMask("deDate");
		$(".numeric").number(true, 2);

		setTimeout(function() {
			doSearch();
		}, 300);
	});
});
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divHeaderHolder" class="ui-layout-north"><%@ include file="/webapp/project/common/include/header.jsp"%></div>
<div id="divBodyHolder" class="ui-layout-center">
<div id="divBodyLeft" class="ui-layout-west"><%@ include file="/webapp/project/common/include/bodyLeft.jsp"%></div>
<div id="divBodyCenter" class="ui-layout-center">
<div id="divFixedPanel">
<div id="divLocationPathArea"><%@ include file="/webapp/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainer">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<tag:buttonGroup id="buttonGroup">
			<tag:button id="btnNew" caption="button.com.new" iconClass="fa-plus-square"/>
			<tag:button id="btnDelete" caption="button.com.delete" iconClass="fa-trash"/>
			<tag:button id="btnSearch" caption="button.com.search" iconClass="fa-search"/>
			<tag:button id="btnClear" caption="button.com.clear" iconClass="fa-refresh"/>
			<tag:button id="btnExport" caption="button.com.export" iconClass="fa-download"/>
		</tag:buttonGroup>
	</div>
</div>
<div id="divAdminToolArea"><%@ include file="/webapp/project/common/include/bodyAdminToolArea.jsp"%></div>
<div id="divSearchCriteriaArea" class="areaContainer">
	<table class="tblSearch">
		<caption><tag:msg key="page.com.searchCriteria"/></caption>
		<colgroup>
			<col width="20%"/>
			<col width="20%"/>
			<col width="30%"/>
			<col width="*"/>
		</colgroup>
		<tr>
			<td class="tdSearch">
				<label for="financialYear" class="lblEn hor mandatory"><tag:msg key="rkm0402.search.financialYear"/></label>
				<div style="float:left;padding-right:4px;">
					<tag:deSelect id="financialYear" name="financialYear" codeType="FinancialYear" selectedValue="<%=selectedFinancialYear%>"/>
				</div>
			</td>
			<td class="tdSearch">
				<label for="quarterName" class="lblEn hor mandatory"><tag:msg key="rkm0402.search.quarter"/></label>
				<div style="float:left;padding-right:4px;">
					<tag:select id="quarterName" name="quarterName" codeType="QUARTER_NAME" selectedValue="<%=selectedQuarterName%>"/>
				</div>
			</td>
			<td class="tdSearch">
				<label for="expenseMainType" class="lblEn hor mandatory"><tag:msg key="rkm0402.search.mainType"/></label>
				<div style="float:left;padding-right:4px;">
					<tag:deSelect id="expenseMainType" name="expenseMainType" codeType="ExpenseMainType" caption="==Select==" orgCategory="<%=orgCategory%>" selectedValue="<%=selectedExpenseMainType%>"/>
				</div>
			</td>
			<td class="tdSearch">
				<label for="expenseSubType" class="lblEn hor mandatory"><tag:msg key="rkm0402.search.subType"/></label>
				<div style="float:left;padding-right:4px;">
					<tag:deSelect id="expenseSubType" name="expenseSubType" codeType="ExpenseSubType" caption="==Select==" orgCategory="<%=orgCategory%>" parentCode="<%=selectedExpenseMainType%>" selectedValue="<%=selectedExpenseSubType%>"/>
				</div>
			</td>
		</tr>
	</table>
</div>
<div id="divInformArea" class="areaContainer">
	<table class="tblDataEntry">
		<caption><tag:msg key="page.com.dataEntry"/></caption>
		<colgroup>
			<col width="9%"/>
			<col width="7%"/>
			<col width="9%"/>
			<col width="9%"/>
			<col width="9%"/>
			<col width="9%"/>
			<col width="9%"/>
			<col width="*"/>
			<col width="4%"/>
		</colgroup>
		<tr>
			<th class="thDataEntryCt mandatory"><tag:msg key="rkm0402.de.date"/></th>
			<th class="thDataEntryCt mandatory"><tag:msg key="rkm0402.de.types"/></th>
			<th class="thDataEntryCt"><tag:msg key="rkm0402.de.mainType"/></th>
			<th class="thDataEntryCt"><tag:msg key="rkm0402.de.subType"/></th>
			<th class="thDataEntryCt mandatory"><tag:msg key="rkm0402.de.grossExpense"/></th>
			<th class="thDataEntryCt mandatory"><tag:msg key="rkm0402.de.gst"/></th>
			<th class="thDataEntryCt"><tag:msg key="rkm0402.de.netExpense"/></th>
			<th class="thDataEntryCt mandatory"><tag:msg key="rkm0402.de.remark"/></th>
			<th class="thDataEntryCt"><tag:msg key="rkm0402.de.action"/></th>
		</tr>
		<tr>
			<td class="tdDataEntryCt">
				<div style="display:inline-block;">
					<input type="text" id="deDate" name="deDate" class="txtEnCt hor" style="width:100px" checkName="<tag:msg key="rkm0402.de.date"/>" mandatory option="date"/>
					<i id="icnDataEntryDate" class="fa fa-calendar icnEn hor"></i>
				</div>
			</td>
			<td class="tdDataEntryCt">
				<tag:button id="btnDeTypes" caption="rkm0402.de.expenseTypes" iconClass="fa-caret-down"/>
			</td>
			<td class="tdDataEntryCt">
				<tag:deSelect id="deExpenseMainType" name="deExpenseMainType" codeType="ExpenseMainType" caption="==Select==" orgCategory="<%=orgCategory%>" options="mandatory"/>
			</td>
			<td class="tdDataEntryCt">
				<tag:deSelect id="deExpenseSubType" name="deExpenseSubType" codeType="ExpenseSubType" caption="==Select==" orgCategory="<%=orgCategory%>" parentCode="<%=selectedExpenseMainType%>" options="mandatory"/>
			</td>
			<td class="tdDataEntryCt">
				<input type="text" id="deGrossExpense" name="deGrossExpense" class="txtEnRt numeric" checkName="<tag:msg key="rkm0402.de.grossSales"/>" mandatory option="numeric"/>
			</td>
			<td class="tdDataEntryCt">
				<input type="text" id="deGst" name="deGst" class="txtEnRt numeric" checkName="<tag:msg key="rkm0402.de.gst"/>" mandatory option="numeric"/>
			</td>
			<td class="tdDataEntryCt">
				<input type="text" id="deNetExpense" name="deNetExpense" class="txtDplRt numeric" disabled/>
			</td>
			<td class="tdDataEntryCt">
				<input type="text" id="deRemark" name="deRemark" class="txtEn"/>
			</td>
			<td class="tdDataEntryCt">
				<i id="icnDataEntryAction" class="fa fa-tasks fa-lg icnEn" onclick="doDataEntryAction(this)"></i>
			</td>
		</tr>
	</table>
</div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanel">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainer">
	<table id="tblGrid" class="tblGrid sort autosort">
		<colgroup>
			<col width="2%"/>
			<col width="5%"/>
			<col width="14%"/>
			<col width="14%"/>
			<col width="4%"/>
			<col width="6%"/>
			<col width="6%"/>
			<col width="6%"/>
			<col width="*"/>
			<col width="6%"/>
			<col width="6%"/>
			<col width="3%"/>
		</colgroup>
		<thead>
			<tr>
				<th class="thGrid"><i id="icnCheck" class="fa fa-check-square-o fa-lg icnEn"></i></th>
				<th class="thGrid sortable:date"><tag:msg key="rkm0402.grid.date"/></th>
				<th class="thGrid"><tag:msg key="rkm0402.grid.mainType"/></th>
				<th class="thGrid"><tag:msg key="rkm0402.grid.subType"/></th>
				<th class="thGrid"><tag:msg key="rkm0402.grid.accountCode"/></th>
				<th class="thGrid"><tag:msg key="rkm0402.grid.grossExpense"/></th>
				<th class="thGrid"><tag:msg key="rkm0402.grid.gst"/></th>
				<th class="thGrid"><tag:msg key="rkm0402.grid.netExpense"/></th>
				<th class="thGrid"><tag:msg key="rkm0402.grid.remark"/></th>
				<th class="thGrid"><tag:msg key="rkm0402.grid.isCompleted"/></th>
				<th class="thGrid sortable:date"><tag:msg key="rkm0402.grid.updateDate"/></th>
				<th class="thGrid"><tag:msg key="page.com.action"/></th>
			</tr>
		</thead>
		<tbody id="tblGridBody">
			<tr>
				<td class="tdGridCt" colspan="12"><tag:msg key="I002"/></td>
			</tr>
		</tbody>
		<tfoot id="tblGridFoot" style="font-weight:bold;">
		</tfoot>
	</table>
	<div id="divPagingArea"></div>
</div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<div id="divBodyRight" class="ui-layout-east"><%@ include file="/webapp/project/common/include/bodyRight.jsp"%></div>
</div>
<div id="divFooterHolder" class="ui-layout-south"><%@ include file="/webapp/project/common/include/footer.jsp"%></div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>