<%/************************************************************************************************
* Description - Bst0202 - Bank Transaction
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	DataSet bankAccnt = (DataSet)paramEntity.getObject("bankAccnt");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconHKAccount.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnUpload" caption="button.com.upload" iconClass="fa-upload"/>
			<ui:button id="btnDiscard" caption="Discard" iconClass="fa-trash"/>
			<ui:button id="btnSave" caption="button.com.save" iconClass="fa-save"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea" class="areaContainerPopup">
	<table class="tblSearch">
		<caption>Please select bank account and a file to upload</caption>
		<colgroup>
			<col width="10%"/>
			<col width="40%"/>
			<col width="10%"/>
			<col width="*"/>
		</colgroup>
		<tr>
			<th class="thSearch rt mandatory">Bank Account</th>
			<td class="tdSearch">
				<ui:select name="bankAccntId" checkName="Bank Account" options="mandatory">
<%
				for (int i=0; i<bankAccnt.getRowCnt(); i++) {
%>
					<option value="<%=bankAccnt.getValue(i, "BANK_ACCNT_ID")%>" bankCode="<%=bankAccnt.getValue(i, "BANK_CODE")%>"><%=bankAccnt.getValue(i, "DESCRIPTION")%></option>
<%
				}
%>
				</ui:select>
			</td>
			<th class="thSearch rt mandatory">Select File</th>
			<td class="tdSearch"><ui:file name="bankStatementFile" style="width:420px;" checkName="Bank Statement File" options="mandatory"/></td>
		</tr>
	</table>
</div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<div id="div_CBA_ANZ" style="display:none">
		<table id="tblGrid_CBA_ANZ" class="tblGrid sort autosort">
			<colgroup>
				<col width="*"/>
				<col width="6%"/>
				<col width="9%"/>
				<col width="9%"/>
				<col width="6%"/>
				<col width="7%"/>
				<col width="7%"/>
				<col width="9%"/>
				<col width="15%"/>
			</colgroup>
			<thead>
				<tr>
					<th class="thGrid">Bank</th>
					<th class="thGrid">BSB</th>
					<th class="thGrid">Account Number</th>
					<th class="thGrid">Account Name</th>
					<th class="thGrid">Row No.</th>
					<th class="thGrid">Date</th>
					<th class="thGrid">Amount</th>
					<th class="thGrid">Balance</th>
					<th class="thGrid">Description</th>
				</tr>
			</thead>
			<tbody id="tblGridBody_CBA_ANZ">
				<tr>
					<td class="tdGrid Ct" colspan="9">&nbsp;</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>