/**************************************************************************************************
 * project
 * Description - Sba0404 - Income Type
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sba.sba0404;

import zebra.data.ParamEntity;

public interface Sba0404Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getUpdate(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeUpdate(ParamEntity paramEntity) throws Exception;
}