<%/************************************************************************************************
* Description - Sys0406 - User
*   - Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/webapp/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	String keyFieldId = requestDataSet.getValue("keyFieldId");
	String valueFieldId = requestDataSet.getValue("valueFieldId");
	String popupToSetValue = requestDataSet.getValue("popupToSetValue");
	String popupName = requestDataSet.getValue("popupName");
	String lookupValue = requestDataSet.getValue("lookupValue");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<tag:cp key="imgIcon"/>/favicon.png">
<title><tag:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/webapp/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript">
var keyFieldId = "<%=keyFieldId%>";
var valueFieldId = "<%=valueFieldId%>";
var popupName = "<%=popupName%>";
var popupToSetValue = eval("<%=popupToSetValue%>");
var lookupValue = "<%=lookupValue%>";
var popupObject = eval(popupName);

$(function() {
	/*!
	 * event
	 */
	/*!
	 * process
	 */
	doSearch = function() {
		commonJs.showProcMessageOnElement("tblGrid");

		setTimeout(function() {
			commonJs.ajaxSubmit({
				url:"/common/lookup/getOrganisationLookup.do",
				dataType:"json",
				formId:"fmDefault",
				success:function(data, textStatus) {
					var result = commonJs.parseAjaxResult(data, textStatus, "json");

					if (result.isSuccess == true || result.isSuccess == "true") {
						renderDataGridTable(result);
					}
				}
			});
		}, 100);
	};

	renderDataGridTable = function(result) {
		var ds = result.dataSet;
		var html = "";

		searchResultDataCount = ds.getRowCnt();
		$("#tblGridBody").html("");

		if (ds.getRowCnt() > 0) {
			for (var i=0; i<ds.getRowCnt(); i++) {
				html += "<tr>";
				html += "<td class=\"tdGridCt\">"+ds.getValue(i, "ORG_ID")+"</td>";
				html += "<td class=\"tdGrid\"><a onclick=\"setValue('"+ds.getValue(i, "ORG_ID")+"', '"+ds.getValue(i, "LEGAL_NAME")+"')\" class=\"aEn\">"+commonJs.abbreviate(ds.getValue(i, "LEGAL_NAME"), 60)+"</a></td>";
				html += "<td class=\"tdGridCt\">"+commonJs.getFormatString(ds.getValue(i, "ABN"), "?? ??? ??? ???")+"</td>";
				html += "<td class=\"tdGrid\">"+commonJs.abbreviate(ds.getValue(i, "POSTAL_ADDRESS"), 60)+"</td>";
				html += "</tr>";
			}
		} else {
			html += "<tr>";
			html += "<td class=\"tdGridCt\" colspan=\"4\"><tag:msg key="I001"/></td>";
			html += "</tr>";
		}

		$("#tblGridBody").append($(html));
		if (commonJs.browser.FireFox) {
			gridWidthAdjust = -34;
		} else {
			gridWidthAdjust = -38;
		}

		$("#tblGrid").fixedHeaderTable({
			baseDivElement:"divScrollablePanelPopup",
			attachedPagingArea:true,
			blockElementId:"tblGrid",
			pagingAreaId:"divPagingArea",
			totalResultRows:result.totalResultRows,
			script:"doSearch",
			widthAdjust:gridWidthAdjust
		});

		commonJs.hideProcMessageOnElement("tblGrid");
	};

	setValue = function(id, name) {
		var targetDocument, keyField, valueField;

		if (popupToSetValue != null) {
			targetDocument = $(popupToSetValue.popupIframe).contents();
			keyField = $(targetDocument).find("#"+keyFieldId);
			valueField = $(targetDocument).find("#"+valueFieldId);

			$(keyField).val(id);
			$(valueField).val(name);
		} else {
		}

		popupObject.close();
	};

	/*!
	 * load event (document / window)
	 */
	$(window).load(function() {
		$("#orgName").val(lookupValue);
		$("#orgName").focus();

		commonJs.setAutoComplete($("#orgName"), {
			method:"getOrgName",
			label:"org_name",
			value:"org_name",
			focus: function(event, ui) {
				$("#orgName").val(ui.item.label);
				return false;
			},
			select:function(event, ui) {
				doSearch();
			}
		});

		commonJs.setAutoComplete($("#abn"), {
			method:"getAbn",
			label:"abn",
			value:"abn",
			focus: function(event, ui) {
				$("#abn").val(ui.item.label);
				return false;
			},
			select:function(event, ui) {
				doSearch();
			}
		});

		setTimeout(function() {
			doSearch();
		}, 400);
	});
});
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/webapp/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight"></div>
</div>
<div id="divSearchCriteriaArea" class="areaContainerPopup">
	<table class="tblSearch">
		<caption><tag:msg key="page.com.searchCriteria"/></caption>
		<colgroup>
			<col width="50%"/>
			<col width="50%"/>
		</colgroup>
		<tr>
			<td class="tdSearch">
				<label for="orgName" class="lblEn hor"><tag:msg key="orglookup.search.orgName"/></label>
				<input type="text" id="orgName" name="orgName" class="txtEn" style="width:250px;"/>
			</td>
			<td class="tdSearch">
				<label for="abn" class="lblEn hor"><tag:msg key="orglookup.search.abn"/></label>
				<input type="text" id="abn" name="abn" class="txtEn" style="width:250px;"/>
			</td>
		</tr>
	</table>
</div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<table id="tblGrid" class="tblGrid sort">
		<colgroup>
			<col width="13%"/>
			<col width="32%"/>
			<col width="13%"/>
			<col width="*"/>
		</colgroup>
		<thead>
			<tr>
				<th class="thGridCt"><tag:msg key="orglookup.grid.id"/></th>
				<th class="thGrid"><tag:msg key="orglookup.grid.name"/></th>
				<th class="thGrid"><tag:msg key="orglookup.grid.abn"/></th>
				<th class="thGrid"><tag:msg key="orglookup.grid.address"/></th>
			</tr>
		</thead>
		<tbody id="tblGridBody">
			<tr>
				<td class="tdGridCt" colspan="4"><tag:msg key="I002"/></td>
			</tr>
		</tbody>
	</table>
	<div id="divPagingArea" class="areaContainer"></div>
</div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>