<%/************************************************************************************************
* Description - Sys0202 - 
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	String codeCategory = requestDataSet.getValue("codeCategory");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconHKAccount.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
#liDummy {display:none;}
#divDataArea.areaContainerPopup {padding-top:0px;}
.dummyDetail {list-style:none;margin-top:4px;}
.dragHandler {cursor:move;}
.deleteButton {cursor:pointer;}
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnSave" caption="button.com.save" iconClass="fa-save"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea" class="areaContainerPopup">
	<table class="tblEdit">
		<caption class="captionEdit"><mc:msg key="sys0202.searchHeader.codeType"/></caption>
		<colgroup>
			<col width="13%"/>
			<col width="*"/>
			<col width="13%"/>
			<col width="15%"/>
			<col width="11%"/>
			<col width="10%"/>
		</colgroup>
		<tr>
			<th class="thEdit rt mandatory"><mc:msg key="sys0202.header.codeType"/></th>
			<td class="tdEdit"><ui:text name="codeTypeMaster" id="codeTypeMaster" className="defClass" style="text-transform:uppercase;" checkName="sys0202.header.codeType" options="mandatory"/></td>
			<th class="thEdit rt mandatory"><mc:msg key="sys0202.header.codeCategory"/></th>
			<td class="tdEdit"><ui:ccselect id="codeCategory" name="codeCategory" codeType="CODE_CATEGORY" selectedValue="<%=codeCategory%>"/></td>
			<th class="thEdit rt mandatory"><mc:msg key="sys0202.header.isActive"/></th>
			<td class="tdEdit"><ui:ccradio name="isActiveMaster" codeType="SIMPLE_YN" selectedValue="Y"/></td>
		</tr>
		<tr>
			<th class="thEdit rt mandatory"><mc:msg key="sys0202.header.descriptionEn"/></th>
			<td class="tdEdit"><ui:text name="descriptionEnMaster" id="descriptionEnMaster" className="defClass" checkName="sys0202.header.descriptionEn" options="mandatory"/></td>
			<th class="thEdit rt mandatory"><mc:msg key="sys0202.header.descriptionKo"/></th>
			<td class="tdEdit" colspan="3"><ui:text name="descriptionKoMaster" id="descriptionKoMaster" className="defClass" checkName="sys0202.header.descriptionKo" options="mandatory"/></td>
		</tr>
	</table>
</div>
<div class="breaker" style="height:5px;"></div>
<div class="divButtonArea areaContainerPopup">
	<div class="divButtonAreaLeft"></div>
	<div class="divButtonAreaRight">
		<ui:buttonGroup id="subButtonGroup">
			<ui:button id="btnAdd" caption="button.com.add" iconClass="fa-plus"/>
		</ui:buttonGroup>
	</div>
</div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<ul id="ulCommonCodeDetailHolder"></ul>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
<li id="liDummy" class="dummyDetail">
	<table class="tblEdit">
		<colgroup>
			<col width="3%"/>
			<col width="13%"/>
			<col width="*"/>
			<col width="13%"/>
			<col width="15%"/>
			<col width="11%"/>
			<col width="10%"/>
		</colgroup>
		<tr>
			<th id="thDragHander" class="thEdit Ct dragHandler" title="<mc:msg key="sys0202.msg.drag"/>"><ui:icon id="iDragHandler" className="fa-lg fa-sort"/></th>
			<th class="thEdit rt mandatory"><mc:msg key="sys0202.header.commonCode"/></th>
			<td class="tdEdit"><ui:text name="commonCodeDetail" id="commonCodeDetail" className="defClass" style="text-transform:uppercase;" checkName="sys0202.header.commonCode" options="mandatory"/></td>
			<th class="thEdit rt mandatory"><mc:msg key="sys0202.header.isActive"/></th>
			<td class="tdEdit"><ui:ccradio name="isActiveDetail" codeType="SIMPLE_YN" selectedValue="Y"/></td>
			<th class="thEdit rt mandatory"><mc:msg key="sys0202.header.sortOrder"/></th>
			<td class="tdEdit"><ui:text name="sortOrderDetail" id="sortOrderDetail" className="defClass" checkName="sys0202.header.sortOrder" options="mandatory" option="numeric"/></td>
		</tr>
		<tr>
			<th id="thDeleteButton" class="thEdit Ct deleteButton" title="<mc:msg key="sys0202.msg.delete"/>"><ui:icon id="iDeleteButton" className="fa-lg fa-times"/></th>
			<th class="thEdit rt mandatory"><mc:msg key="sys0202.header.descriptionEn"/></th>
			<td class="tdEdit"><ui:text name="descriptionEnDetail" id="descriptionEnDetail" className="defClass" checkName="sys0202.header.descriptionEn" options="mandatory"/></td>
			<th class="thEdit rt mandatory"><mc:msg key="sys0202.header.descriptionKo"/></th>
			<td class="tdEdit" colspan="3"><ui:text name="descriptionKoDetail" id="descriptionKoDetail" className="defClass" checkName="sys0202.header.descriptionKo" options="mandatory"/></td>
		</tr>
	</table>
</li>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>