/**************************************************************************************************
 * project
 * Description - Rkm0606 - Lending
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.rkm.rkm0606;

import zebra.data.ParamEntity;

public interface Rkm0606Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getEdit(ParamEntity paramEntity) throws Exception;
	public ParamEntity getFile(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeSave(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeComplete(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeDelete(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeExport(ParamEntity paramEntity) throws Exception;
}