/**************************************************************************************************
 * project
 * Description - Sba0414 - Lending Type
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sba.sba0414;

import org.springframework.beans.factory.annotation.Autowired;

import project.common.extend.BaseAction;

public class Sba0414Action extends BaseAction {
	@Autowired
	private Sba0414Biz biz;

	public String getDefault() throws Exception {
		biz.getDefault(paramEntity);
		return "list";
	}

	public String getList() throws Exception {
		try {
			biz.getList(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String getUpdate() throws Exception {
		biz.getUpdate(paramEntity);
		return "update";
	}

	public String exeUpdate() throws Exception {
		try {
			biz.exeUpdate(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String exeSave() throws Exception {
		try {
			biz.exeSave(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}
}