<%/************************************************************************************************
* Description - Sys0402 - Menu
*   - Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/webapp/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet quickMenuDataSet = MenuManager.getQuickMenu();
	DataSet menuDataSet = MenuManager.getMenuDataSetByLevel(1);
	String langCode = CommonUtil.upperCase((String)session.getAttribute("langCode"));
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<tag:cp key="imgIcon"/>/favicon.png">
<title><tag:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/webapp/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript">
var popup = null;
var searchResultDataCount = 0;
var langCode = commonJs.upperCase(globalMap.get("langCode"));

$(function() {
	/*!
	 * event
	 */
	$("#btnNew").click(function(event) {
		openPopup({mode:"New"});
	});

	$("#btnDelete").click(function(event) {
		doDelete();
	});

	$("#btnSearch").click(function(event) {
		doSearch();
	});

	$("#btnClear").click(function(event) {
		commonJs.clearSearchCriteria();
	});

	$("#icnCheck").click(function(event) {
		commonJs.toggleCheckboxes("chkForDel");
	});

	$("#btnSetSort").click(function(event) {
		openPopup({mode:"SetSort"});
	});

	$("#searchMenu").change(function() {
		doSearch();
	});

	$(document).keypress(function(event) {
		if (event.which == 13) {
			var element = event.target;
		}
	});

	/*!
	 * context menus
	 */
	setExportButtonContextMenu = function() {
		ctxMenu.commonExport[0].fun = function() {exeExport(ctxMenu.commonExport[0]);};
		ctxMenu.commonExport[1].fun = function() {exeExport(ctxMenu.commonExport[1]);};
		ctxMenu.commonExport[2].fun = function() {exeExport(ctxMenu.commonExport[2]);};
		ctxMenu.commonExport[3].fun = function() {exeExport(ctxMenu.commonExport[3]);};
		ctxMenu.commonExport[4].fun = function() {exeExport(ctxMenu.commonExport[4]);};
		ctxMenu.commonExport[5].fun = function() {exeExport(ctxMenu.commonExport[5]);};

		$("#btnExport").contextMenu(ctxMenu.commonExport, {
			classPrefix:"actionButton",
			effectDuration:300,
			effect:"slide",
			borderRadius:"bottom 4px",
			displayAround:"trigger",
			position:"bottom",
			horAdjust:0,
			verAdjust:0
		});
	};

	/*!
	 * process
	 */
	doSearch = function() {
		commonJs.showProcMessageOnElement("tblGrid");
		commonJs.ajaxSubmit({
			url:"/sys/0402/getList.do",
			dataType:"json",
			formId:"fmDefault",
			blockElementId:"tblGrid",
			success:function(data, textStatus) {
				var result = commonJs.parseAjaxResult(data, textStatus, "json");

				if (result.isSuccess == true || result.isSuccess == "true") {
					setTimeout(function() {
						renderDataGridTable(result);
					}, 100);
				}
			}
		});
	};

	renderDataGridTable = function(result) {
		var dataSet = result.dataSet;
		var html = "", delimiter = "_";

		searchResultDataCount = dataSet.getRowCnt();
		$("#gridBody").html("");

		if (dataSet.getRowCnt() > 0) {
			for (var i=0; i<dataSet.getRowCnt(); i++) {
				var menuPath = dataSet.getValue(i, "PATH");
				var menuId = dataSet.getValue(i, "MENU_ID");
				var menuName = dataSet.getValue(i, "MENU_NAME_"+langCode);
				var deletable = dataSet.getValue(i, "DELETABLE");
				var className = "chkEn", disabledStr = "";
				var space = "", style = "", paramValue = "";
				var iLevel = parseInt(dataSet.getValue(i, "MENU_LEVEL")) - 1;

				style = (iLevel == 0 || iLevel == 1) ? "font-weight:bold;" : "";
				for (var j=0; j<iLevel; j++) {
					space += "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
				}

				if (!commonJs.toBoolean(deletable)) {
					className = "chkDis";
					disabledStr = "disabled";
				}

				paramValue = dataSet.getValue(i, "MENU_LEVEL")+delimiter+menuPath+delimiter+menuId+delimiter+deletable;

				html += "<tr>";
				html += "<td class=\"tdGridCt\"><input type=\"checkbox\" id=\"chkForDel\" name=\"chkForDel\" class=\""+className+" inTblGrid\" value=\""+paramValue+"\" "+disabledStr+"/></td>";
				html += "<td class=\"tdGrid\" style=\""+style+"\">"+space+"<a onclick=\"getDetail('"+paramValue+"')\" class=\"aEn\">"+menuId+"</a></td>";
				html += "<td class=\"tdGrid\" style=\""+style+"\">"+menuName+"</td>";
				html += "<td class=\"tdGrid\">"+dataSet.getValue(i, "MENU_URL")+"</td>";
				html += "<td class=\"tdGridCt\">"+dataSet.getValue(i, "SORT_ORDER")+"</td>";
				html += "<td class=\"tdGrid\">"+dataSet.getValue(i, "DESCRIPTION")+"</td>";
				html += "<td class=\"tdGridCt\">"+dataSet.getValue(i, "IS_ACTIVE")+"</td>";
				html += "<td class=\"tdGridCt\"><i id=\"icnAction\" name=\"icnAction\" class=\"fa fa-tasks fa-lg icnEn\" paramValue=\""+paramValue+"\" deletable=\""+deletable+"\" onclick=\"doAction(this)\"></i></td>";
				html += "</tr>";
			}
		} else {
			html += "<tr>";
			html += "<td class=\"tdGridCt\" colspan=\"8\"><tag:msg key="I001"/></td>";
			html += "</tr>";
		}

		$("#gridBody").append($(html));
		if (commonJs.browser.FireFox) {
			gridWidthAdjust = 31;
		} else {
			gridWidthAdjust = 32;
		}

		$("#tblGrid").fixedHeaderTable({
			baseDivElement:"divScrollablePanel",
			blockElementId:"gridBody",
			totalResultRows:result.totalResultRows,
			script:"doSearch",
			widthAdjust:gridWidthAdjust
		});

		$("[name=icnAction]").each(function(index) {
			$(this).contextMenu(ctxMenu.commonAction);
		});

		commonJs.hideProcMessageOnElement("tblGrid");
	};

	getDetail = function(paramValue) {
		openPopup({mode:"Detail", paramValue:paramValue});
	};

	openPopup = function(param) {
		var url = "", header = "";
		var width = 700, height = 0;

		if (param.mode == "Detail") {
			url = "/sys/0402/getDetail.do";
			header = "<tag:msg key="sys0402.header.popupHeaderDetail"/>";
			height = 300;
		} else if (param.mode == "New") {
			url = "/sys/0402/getInsert.do";
			header = "<tag:msg key="sys0402.header.popupHeaderEdit"/>";
			height = 390;
		} else if (param.mode == "Edit") {
			url = "/sys/0402/getUpdate.do";
			header = "<tag:msg key="sys0402.header.popupHeaderEdit"/>";
			height = 418;
		} else if (param.mode == "SetSort") {
			url = "/sys/0402/getUpdateSortOrder.do";
			header = "<tag:msg key="sys0402.header.popupHeaderSort"/>";
			width = 900;
			height = 710;
		}

		var popParam = {
			popupId:"menu"+param.mode,
			url:url,
			paramData:{
				mode:param.mode,
				paramValue:param.paramValue
			},
			header:header,
			blind:true,
			width:width,
			height:height
		};

		popup = commonJs.openPopup(popParam);
	};

	doDelete = function() {
		if (commonJs.getCountChecked("chkForDel") == 0) {
			commonJs.warn("<tag:msg key="I902"/>");
			return;
		}

		commonJs.confirm({
			contents:"<tag:msg key="Q002"/>",
			buttons:[{
				caption:"Yes",
				callback:function() {
					exeDelete();
				}
			}, {
				caption:"No",
				callback:function() {
				}
			}],
			blind:true
		});
	};

	exeDelete = function() {
		commonJs.ajaxSubmit({
			url:"/sys/0402/exeDelete.do",
			dataType:"json",
			formId:"fmDefault",
			success:function(data, textStatus) {
				var result = commonJs.parseAjaxResult(data, textStatus, "json");

				if (result.isSuccess == true || result.isSuccess == "true") {
					commonJs.openDialog({
						type:"information",
						contents:result.message,
						blind:true,
						buttons:[{
							caption:"Ok",
							callback:function() {
								doSearch();
							}
						}]
					});
				} else {
					commonJs.error(result.message);
				}
			}
		});
	};

	doAction = function(img) {
		var deletable = $(img).attr("deletable");
		var paramValue = $(img).attr("paramValue");

		$("input:checkbox[name=chkForDel]").each(function(index) {
			if (!$(this).is(":disabled") && $(this).val() == paramValue) {
				$(this).prop("checked", true);
			} else {
				$(this).prop("checked", false);
			}
		});

		if (deletable == "true") {
			ctxMenu.commonAction[2].disable = false;
		} else {
			ctxMenu.commonAction[2].disable = true;
		}

		ctxMenu.commonAction[0].fun = function() {getDetail(paramValue);};
		ctxMenu.commonAction[1].fun = function() {openPopup({mode:"Edit", paramValue:paramValue});};
		ctxMenu.commonAction[2].fun = function() {doDelete();};

		$(img).contextMenu(ctxMenu.commonAction, {
			classPrefix:"actionInGrid",
			displayAround:"trigger",
			position:"bottom",
			horAdjust:0,
			verAdjust:2,
			containment:$("#divScrollablePanel")
		});
	};

	exeExport = function(menuObject) {
		$("[name=fileType]").remove();
		$("[name=dataRange]").remove();

		if (searchResultDataCount <= 0) {
			commonJs.warn("<tag:msg key="I001"/>");
			return;
		}

		commonJs.confirm({
			contents:"<tag:msg key="Q003"/>",
			buttons:[{
				caption:"Yes",
				callback:function() {
					commonJs.doSubmit({
						form:"fmDefault",
						action:"/sys/0402/exeExport.do",
						data:{
							fileType:menuObject.fileType,
							dataRange:menuObject.dataRange
						}
					});
				}
			}, {
				caption:"No",
				callback:function() {
				}
			}],
			blind:true
		});
	};

	/*!
	 * load event (document / window)
	 */
	$(window).load(function() {
		setExportButtonContextMenu();

		setTimeout(function() {
			doSearch();
		}, 400);
	});
});
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divHeaderHolder" class="ui-layout-north"><%@ include file="/webapp/project/common/include/header.jsp"%></div>
<div id="divBodyHolder" class="ui-layout-center">
<div id="divBodyLeft" class="ui-layout-west"><%@ include file="/webapp/project/common/include/bodyLeft.jsp"%></div>
<div id="divBodyCenter" class="ui-layout-center">
<div id="divFixedPanel">
<div id="divLocationPathArea"><%@ include file="/webapp/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainer">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<tag:buttonGroup id="buttonGroup">
			<tag:button id="btnSetSort" caption="sys0402.btn.sort" iconClass="fa-sort-numeric-asc"/>
			<tag:button id="btnNew" caption="button.com.new" iconClass="fa-plus-square"/>
			<tag:button id="btnDelete" caption="button.com.delete" iconClass="fa-trash"/>
			<tag:button id="btnSearch" caption="button.com.search" iconClass="fa-search"/>
			<tag:button id="btnClear" caption="button.com.clear" iconClass="fa-refresh"/>
			<tag:button id="btnExport" caption="button.com.export" iconClass="fa-download"/>
		</tag:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea" class="areaContainer">
	<table class="tblSearch">
		<caption><tag:msg key="page.com.searchCriteria"/></caption>
		<tr>
			<td class="tdSearch">
				<label for="searchMenu" class="lblEn hor"><tag:msg key="sys0402.search.searchType"/></label>
				<select id="searchMenu" name="searchMenu" class="bootstrapSelect default">
					<option value="">==Select==</option>
<%
				for (int i=0; i<menuDataSet.getRowCnt(); i++) {
%>
					<option value="<%=menuDataSet.getValue(i, "MENU_ID")%>"><%=menuDataSet.getValue(i, "MENU_NAME_"+langCode)%>(<%=menuDataSet.getValue(i, "MENU_ID")%>)</option>
<%
				}
%>
				</select>
			</td>
		</tr>
	</table>
</div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanel">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainer">
	<table id="tblGrid" class="tblGrid">
		<colgroup>
			<col width="2%"/>
			<col width="9%"/>
			<col width="20%"/>
			<col width="15%"/>
			<col width="7%"/>
			<col width="*"/>
			<col width="5%"/>
			<col width="3%"/>
		</colgroup>
		<thead>
			<tr>
				<th class="thGrid"><i id="icnCheck" class="fa fa-check-square-o fa-lg icnEn" title="<tag:msg key="page.com.selectToDelete"/>"></i></th>
				<th class="thGrid"><tag:msg key="sys0402.grid.menuId"/></th>
				<th class="thGrid"><tag:msg key="sys0402.grid.menuName"/></th>
				<th class="thGrid"><tag:msg key="sys0402.grid.menuUrl"/></th>
				<th class="thGrid"><tag:msg key="sys0402.grid.sortOrder"/></th>
				<th class="thGrid"><tag:msg key="sys0402.grid.menuDesc"/></th>
				<th class="thGrid"><tag:msg key="sys0402.grid.isActive"/></th>
				<th class="thGrid"><tag:msg key="page.com.action"/></th>
			</tr>
		</thead>
		<tbody id="gridBody">
			<tr>
				<td class="tdGridCt" colspan="8"><tag:msg key="I002"/></td>
			</tr>
		</tbody>
	</table>
	<div id="divPagingArea"></div>
</div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<div id="divBodyRight" class="ui-layout-east"><%@ include file="/webapp/project/common/include/bodyRight.jsp"%></div>
</div>
<div id="divFooterHolder" class="ui-layout-south"><%@ include file="/webapp/project/common/include/footer.jsp"%></div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>