<%/************************************************************************************************
* Description - Rkm0404 - Asset Expense
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	String orgCategory = CommonUtil.nvl((String)session.getAttribute("OrgCategoryForAdminTool"), (String)session.getAttribute("OrgCategory"));
	String defaultPeriodYear = (String)session.getAttribute("DefaultPeriodYear");
	String defaultQuarterName = (String)session.getAttribute("DefaultQuarterName");
	String paramFinancialYear = requestDataSet.getValue("financialYear");
	String paramQuarterName = requestDataSet.getValue("quarterName");
	String paramAssetType = requestDataSet.getValue("assetType");
	String selectedFinancialYear = CommonUtil.nvl(paramFinancialYear, defaultPeriodYear);
	String selectedQuarterName = CommonUtil.nvl(paramQuarterName, defaultQuarterName);
	String selectedAssetType = CommonUtil.nvl(paramAssetType);
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconHKAccount.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divHeaderHolder" class="ui-layout-north"><%@ include file="/project/common/include/header.jsp"%></div>
<div id="divBodyHolder" class="ui-layout-center">
<div id="divBodyLeft" class="ui-layout-west"><%@ include file="/project/common/include/bodyLeft.jsp"%></div>
<div id="divBodyCenter" class="ui-layout-center">
<div id="divFixedPanel">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainer">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnNew" caption="button.com.new" iconClass="fa-plus-square"/>
			<ui:button id="btnDelete" caption="button.com.delete" iconClass="fa-trash"/>
			<ui:button id="btnSearch" caption="button.com.search" iconClass="fa-search"/>
			<ui:button id="btnClear" caption="button.com.clear" iconClass="fa-refresh"/>
			<ui:button id="btnExport" caption="button.com.export" iconClass="fa-download"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divAdminToolArea"><%@ include file="/project/common/include/bodyAdminToolArea.jsp"%></div>
<div id="divSearchCriteriaArea" class="areaContainer">
	<table class="tblSearch">
		<caption><mc:msg key="page.com.searchCriteria"/></caption>
		<colgroup>
			<col width="33%"/>
			<col width="33%"/>
			<col width="*"/>
		</colgroup>
		<tr>
			<td class="tdSearch">
				<label for="financialYear" class="lblEn hor mandatory"><mc:msg key="rkm0404.search.financialYear"/></label>
				<div style="float:left;padding-right:4px;">
					<ui:deSelect name="financialYear" codeType="FinancialYear" selectedValue="<%=selectedFinancialYear%>"/>
				</div>
			</td>
			<td class="tdSearch">
				<label for="quarterName" class="lblEn hor mandatory"><mc:msg key="rkm0404.search.quarter"/></label>
				<div style="float:left;padding-right:4px;">
					<ui:ccselect name="quarterName" codeType="QUARTER_NAME" selectedValue="<%=selectedQuarterName%>"/>
				</div>
			</td>
			<td class="tdSearch">
				<label for="assetType" class="lblEn hor mandatory"><mc:msg key="rkm0404.search.assetType"/></label>
				<div style="float:left;padding-right:4px;">
					<ui:deSelect name="assetType" codeType="AssetType" caption="==Select==" orgCategory="<%=orgCategory%>" selectedValue="<%=selectedAssetType%>"/>
				</div>
			</td>
		</tr>
	</table>
</div>
<div id="divInformArea" class="areaContainer">
	<table class="tblDataEntry">
		<caption><mc:msg key="page.com.dataEntry"/></caption>
		<colgroup>
			<col width="9%"/>
			<col width="9%"/>
			<col width="9%"/>
			<col width="9%"/>
			<col width="9%"/>
			<col width="9%"/>
			<col width="12%"/>
			<col width="*"/>
			<col width="4%"/>
		</colgroup>
		<tr>
			<th class="thDataEntry mandatory"><mc:msg key="rkm0404.de.date"/></th>
			<th class="thDataEntry mandatory"><mc:msg key="rkm0404.de.assetType"/></th>
			<th class="thDataEntry mandatory"><mc:msg key="rkm0404.de.assetType"/></th>
			<th class="thDataEntry mandatory"><mc:msg key="rkm0404.de.grossAsset"/></th>
			<th class="thDataEntry mandatory"><mc:msg key="rkm0404.de.gst"/></th>
			<th class="thDataEntry"><mc:msg key="rkm0404.de.netAsset"/></th>
			<th class="thDataEntry"><mc:msg key="rkm0404.de.fileAttach"/></th>
			<th class="thDataEntry"><mc:msg key="rkm0404.de.remark"/></th>
			<th class="thDataEntry"><mc:msg key="rkm0404.de.action"/></th>
		</tr>
		<tr>
			<td class="tdDataEntry Ct">
				<div style="display:inline-block;">
					<ui:text name="deDate" className="hor" style="width:100px" checkName="rkm0404.de.date" options="mandatory" option="date"/>
					<ui:icon id="icnDataEntryDate" className="fa-calendar hor"/>
				</div>
			</td>
			<td class="tdDataEntry Ct"><ui:button id="btnDeAssetType" caption="rkm0404.de.assetType" iconClass="fa-caret-down"/></td>
			<td class="tdDataEntry Ct"><ui:deSelect name="deAssetType" codeType="AssetType" caption="==Select==" orgCategory="<%=orgCategory%>" options="mandatory"/></td>
			<td class="tdDataEntry Ct"><ui:text name="deGrossAsset" className="rt numeric" checkName="rkm0404.de.grossAsset" options="mandatory" option="numeric"/></td>
			<td class="tdDataEntry Ct"><ui:text name="deGst" className="rt numeric" checkName="rkm0404.de.gst" options="mandatory" option="numeric"/></td>
			<td class="tdDataEntry Ct"><ui:text name="deNetAsset" className="rt numeric" status="display"/></td>
			<td class="tdDataEntry Ct"><ui:file name="deFile" style="width:200px"/></td>
			<td class="tdDataEntry Ct"><ui:text name="deRemark"/></td>
			<td class="tdDataEntry Ct"><ui:icon id="icnDataEntryAction" className="fa-tasks fa-lg" script="doDataEntryAction(this)"/></td>
		</tr>
	</table>
</div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanel">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainer">
	<table id="tblGrid" class="tblGrid sort autosort">
		<colgroup>
			<col width="2%"/>
			<col width="5%"/>
			<col width="14%"/>
			<col width="4%"/>
			<col width="6%"/>
			<col width="6%"/>
			<col width="6%"/>
			<col width="6%"/>
			<col width="*"/>
			<col width="6%"/>
			<col width="6%"/>
			<col width="3%"/>
		</colgroup>
		<thead>
			<tr>
				<th class="thGrid"><ui:icon id="icnCheck" className="fa-check-square-o fa-lg"/></th>
				<th class="thGrid"><mc:msg key="rkm0404.grid.date"/></th>
				<th class="thGrid"><mc:msg key="rkm0404.grid.assetType"/></th>
				<th class="thGrid"><mc:msg key="rkm0404.grid.accountCode"/></th>
				<th class="thGrid"><mc:msg key="rkm0404.grid.grossAsset"/></th>
				<th class="thGrid"><mc:msg key="rkm0404.grid.gst"/></th>
				<th class="thGrid"><mc:msg key="rkm0404.grid.netAsset"/></th>
				<th class="thGrid"><mc:msg key="rkm0404.grid.fileCnt"/></th>
				<th class="thGrid"><mc:msg key="rkm0404.grid.remark"/></th>
				<th class="thGrid"><mc:msg key="rkm0404.grid.isCompleted"/></th>
				<th class="thGrid"><mc:msg key="rkm0404.grid.updateDate"/></th>
				<th class="thGrid"><mc:msg key="page.com.action"/></th>
			</tr>
		</thead>
		<tbody id="tblGridBody">
			<tr>
				<td class="tdGridCt" colspan="12"><mc:msg key="I002"/></td>
			</tr>
		</tbody>
		<tfoot id="tblGridFoot" style="font-weight:bold;">
		</tfoot>
	</table>
</div>
<div id="divPagingArea" class="areaContainer"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<div id="divBodyRight" class="ui-layout-east"><%@ include file="/project/common/include/bodyRight.jsp"%></div>
</div>
<div id="divFooterHolder" class="ui-layout-south"><%@ include file="/project/common/include/footer.jsp"%></div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>