/**************************************************************************************************
 * project
 * Description - Ads0204 - Invoice Management
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.ads.ads0204;

import zebra.data.ParamEntity;

public interface Ads0204Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getEdit(ParamEntity paramEntity) throws Exception;

	public ParamEntity doSave(ParamEntity paramEntity) throws Exception;
	public ParamEntity doDelete(ParamEntity paramEntity) throws Exception;
	public ParamEntity doExport(ParamEntity paramEntity) throws Exception;
}