/**************************************************************************************************
 * project
 * Description - Bbs0202 - Announcement
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.cst.cst0202;

import zebra.data.ParamEntity;

public interface Cst0202Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getChart(ParamEntity paramEntity) throws Exception;
}