/**************************************************************************************************
 * project
 * Description - Sys0816 - Tax Table Mgmt.
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sys0816;

import zebra.data.ParamEntity;

public interface Sys0816Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getUpload(ParamEntity paramEntity) throws Exception;
	public ParamEntity getInsert(ParamEntity paramEntity) throws Exception;
	public ParamEntity getUpdate(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeInsert(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeUpdate(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeDelete(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeExport(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeFileUpload(ParamEntity paramEntity) throws Exception;
}