/**************************************************************************************************
 * project
 * Description - Bst0202 - Bank Transaction
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.bst.bst0202;

import org.springframework.beans.factory.annotation.Autowired;

import project.common.extend.BaseAction;

public class Bst0202Action extends BaseAction {
	@Autowired
	private Bst0202Biz biz;

	public String getDefault() throws Exception {
		biz.getDefault(paramEntity);
		return "list";
	}

	public String getList() throws Exception {
		try {
			biz.getList(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}
}