<%/************************************************************************************************
* Description - Sba0412 - Borrowing Type
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	SysBorrowingType sysBorrowingType = (SysBorrowingType)paramEntity.getObject("sysBorrowingType");
	String gstFormat = "#,##0.00";
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconHKAccount.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnSave" caption="button.com.save" iconClass="fa-save"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<table class="tblEdit">
		<colgroup>
			<col width="18%"/>
			<col width="32%"/>
			<col width="18%"/>
			<col width="32%"/>
		</colgroup>
		<tr>
			<th class="thEdit Rt mandatory"><mc:msg key="sba0412.header.borrowingTypeId"/></th>
			<td class="tdEdit">
				<ui:text name="borrowingTypeId" value="<%=sysBorrowingType.getBorrowingTypeId()%>" status="display" checkName="sba0412.header.borrowingTypeId" options="mandatory"/>
			</td>
			<th class="thEdit Rt mandatory"><mc:msg key="sba0412.header.orgCategory"/></th>
			<td class="tdEdit">
				<ui:ccselect name="orgCategory" codeType="ORG_CATEGORY" status="disabled" selectedValue="<%=sysBorrowingType.getOrgCategory()%>" checkName="sba0412.header.orgCategory" options="mandatory"/>
			</td>
		</tr>
		<tr>
			<th class="thEdit Rt mandatory"><mc:msg key="sba0412.header.borrowingType"/></th>
			<td class="tdEdit">
				<ui:ccselect name="borrowingType" codeType="BORROW_TYPE" status="disabled" selectedValue="<%=sysBorrowingType.getBorrowingType()%>" checkName="sba0412.header.borrowingType" options="mandatory"/>
			</td>
			<th class="thEdit Rt mandatory"><mc:msg key="sba0412.header.description"/></th>
			<td class="tdEdit">
				<ui:text name="description" value="<%=sysBorrowingType.getDescription()%>" checkName="sba0412.header.description" options="mandatory"/>
			</td>
		</tr>
		<tr>
			<th class="thEdit Rt mandatory"><mc:msg key="sba0412.header.isApplyGst"/></th>
			<td class="tdEdit">
				<ui:ccselect name="isApplyGst" codeType="SIMPLE_YN" selectedValue="<%=sysBorrowingType.getIsApplyGst()%>" checkName="sba0412.header.isApplyGst" options="mandatory"/>
			</td>
			<th class="thEdit Rt mandatory"><mc:msg key="sba0412.header.gstPercentage"/></th>
			<td class="tdEdit">
				<ui:text name="gstPercentage" value="<%=CommonUtil.toString(sysBorrowingType.getGstPercentage(), gstFormat)%>" className="numeric" checkName="sba0412.header.gstPercentage" options="mandatory"/>
			</td>
		</tr>
		<tr>
			<th class="thEdit Rt"><mc:msg key="sba0412.header.accountCode"/></th>
			<td class="tdEdit">
				<ui:text name="accountCode" value="<%=sysBorrowingType.getAccountCode()%>" checkName="sba0412.header.accountCode"/>
			</td>
			<th class="thEdit Rt"></th>
			<td class="tdEdit"></td>
		</tr>
	</table>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>